services:
  setsetset-prod:
    container_name: setsetset-prod
    build:
      context: .
      dockerfile: Dockerfile

    networks:
      - setsetset-network

    ports:
      - 8001:8001

    environment:
      SERVER_PORT: 8001
      PAYLOAD_API_URL: http://setsetset-payload:3001/api

networks:
  setsetset-network:
    external: true
